# Generated by Django 4.0 on 2022-09-16 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_alter_car_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='created_data',
            new_name='created_date',
        ),
    ]
